### ISSUE TITLE
Backlog WP 1 to WP 3: #5 Definition of a generic openETCS API

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/SRS-Analysis#44]
Dear Fausto,

please find the 5th priority issue from WP 1 to WP 3: Definition of a generic openETCS API

**Comment by faustco** [comment]
more precisely .... as per FPP
T3.6 Functional model (Leader : DB, formerly ERTMSolutions)
Once identified the overall variables and/or properties managed by any ERTMS On-board solution, it will be necessary to take up with its functional modelling. This model results from the identification of the main functions, and the assignment of the variables and/or properties that they need to manage. As a consequence, we will also identify the data flow exchanged between those function including the API that is to say the functional data as provided to the ERTMS application software in order to be able to manage its internal variables and/or take the proper actions. 
Issue is misplaced
